<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="Components\ActivityCard.razor" />
	  <Content Remove="Components\ActivityChat.razor" />
	  <Content Remove="Components\ActivityFeed.razor" />
	  <Content Remove="Components\Calendar.razor" />
	  <Content Remove="Components\CreateTemplate.razor" />
	  <Content Remove="Components\EditProfile.razor" />
	  <Content Remove="Components\Favorites.razor" />
	  <Content Remove="Components\MyParticipations.razor" />
	  <Content Remove="Components\SearchActivities.razor" />
	  <Content Remove="Components\Subscriptions.razor" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.10" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.14.3" />
	  <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.14.3" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

</Project>